// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rqnjsihfqfscbnoowiru.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbmpzaWhmcWZzY2Jub293aXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4ODc4MzgsImV4cCI6MjA0ODQ2MzgzOH0.E3clN8MUpBolGDExotNwd2lezs2uDZ72_GpCbyoblsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);